services:
  db:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Kyiv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sasha -d testdb" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: todo-app
    depends_on:
      db:
        condition: service_healthy
    environment:

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      TZ: Europe/Kyiv
    ports:
      - "8080:8080"
  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    container_name: todo-cli
    depends_on:
      db:
        condition: service_healthy
    environment:

      SPRING_DATASOURCE_URL: j${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      TZ: Europe/Kyiv
    tty: true
    volumes:
      - "./:/app"
volumes:
  pgdata:
