CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE tasks (
    id BIGSERIAL PRIMARY KEY,
    description VARCHAR(255),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE
);